/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogDestockageAlimentaireCoteDivoireRouteImport } from './routes/blog.destockage-alimentaire-cote-divoire'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDestockageAlimentaireCoteDivoireRoute =
  BlogDestockageAlimentaireCoteDivoireRouteImport.update({
    id: '/blog/destockage-alimentaire-cote-divoire',
    path: '/blog/destockage-alimentaire-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/partenaires': typeof PartenairesRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/destockage-alimentaire-cote-divoire': typeof BlogDestockageAlimentaireCoteDivoireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/partenaires': typeof PartenairesRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/destockage-alimentaire-cote-divoire': typeof BlogDestockageAlimentaireCoteDivoireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/partenaires': typeof PartenairesRoute
  '/reseau': typeof ReseauRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/destockage-alimentaire-cote-divoire': typeof BlogDestockageAlimentaireCoteDivoireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/devis'
    | '/partenaires'
    | '/reseau'
    | '/services'
    | '/sitemap.xml'
    | '/blog/destockage-alimentaire-cote-divoire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/devis'
    | '/partenaires'
    | '/reseau'
    | '/services'
    | '/sitemap.xml'
    | '/blog/destockage-alimentaire-cote-divoire'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/devis'
    | '/partenaires'
    | '/reseau'
    | '/services'
    | '/sitemap.xml'
    | '/blog/destockage-alimentaire-cote-divoire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  PartenairesRoute: typeof PartenairesRoute
  ReseauRoute: typeof ReseauRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogDestockageAlimentaireCoteDivoireRoute: typeof BlogDestockageAlimentaireCoteDivoireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/destockage-alimentaire-cote-divoire': {
      id: '/blog/destockage-alimentaire-cote-divoire'
      path: '/blog/destockage-alimentaire-cote-divoire'
      fullPath: '/blog/destockage-alimentaire-cote-divoire'
      preLoaderRoute: typeof BlogDestockageAlimentaireCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  PartenairesRoute: PartenairesRoute,
  ReseauRoute: ReseauRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogDestockageAlimentaireCoteDivoireRoute:
    BlogDestockageAlimentaireCoteDivoireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
